### ISSUE TITLE
table scrolling

### ISSUE THREAD

**Issue by greenpdx** [matfish2/vue-tables-2#341]
This is a feature request.
I would love to see a table that scrolls. while dynamically accessing data from the server.

**Comment by matfish2** [comment]
I need to think of the best UX for such a feature. 
So I'll share my thoughts here and everyone are welcome to chip in.

First of all, there is a codependency on styling, i.e the user will have to make the `thead` fixed and limit the table height. E.g:

```css
tbody {
    display:block;
    height:200px;
    overflow:auto;
}
thead, tbody tr {
    display:table;
    width:100%;
    table-layout:fixed;/* even columns width , fix width of table too*/
}

thead {
    width: calc( 100% - 1em )/* scrollbar is average 1em/16px width, remove it from thead width */
}
```

As for the functionality itself I see (at least) two options:
1. The table will load with only the first page (as defined by the `perPage` option), and each time the scrollbar hits the bottom it will load the next page and concatenate it to the existing data-set. 

2. The table will load with a scroll bar that *represents* the total count as returned from the server, and with every scroll action will load only the rows that should be visible to the user (again, this depends on styling). Here is a react example I found: http://bvaughn.github.io/react-virtualized/#/components/InfiniteLoader

It terms of UX option 2 seems much better because it allows the user to scroll quickly to any point in the dataset, while option 1 requires a sequential page-by-page load. As you can see in the example, option 2 also allows for smooth scrolling, as it uses placeholders until the server returns the actual data.

So, personally I think option 2 is better, although it seems harder to implement...
