### ISSUE TITLE
Disable Child Row Toggler

### ISSUE THREAD

**Issue by 19peaches** [matfish2/vue-tables-2#649]
- Vue.js version: 2.5.21
- consumed using: (browserify/webpack/rollup) webpack (laravel mix)
- FULL error message (including stack trace): n/a
- relevant code: n/a

I have my own child row toggler implemented in a vue component in my Actions column at the end of each row.

I don't need, nor do I want an extra `th` or `td` at the beginning or the end of the rows.

It seems there should be a `childRowToggler` boolean option so that this can be completely turned off as opposed to just moving it to the front or back.

I guess I can try and use the display css to remove it, but it should be an option for those who wish to implement their own solution.

Thanks.

**Comment by 19peaches** [comment]
For anyone else, this scss worked for me:

```scss
.VueTables {
	.has-child-row {
		thead tr th:first-child,
		tbody tr:not(.VueTables__child-row) td:first-child {
			display: none !important;
		}
	}
}
```
Hope this helps folks till we can disable this feature in the code.
